# This is a basic workflow to help you get started with Actions

name: Deploy Docker image

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Centos7-Python3.8
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ferrosa/centos7-python3.8:latest 
          file: centos7-python3.8/Dockerfile     
      - name: Build and push Centos7-Python3.9
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ferrosa/centos7-python3.9:latest 
          file: centos7-python3.9/Dockerfile  

