name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for python 3.9
      run: docker build centos7-python3.9 --file Dockerfile --tag ferrosa/centos7-python3.9:$(date +%s)
